version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:8.12.0
    environment:
      - discovery.type=single-node
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}
    ports:
      - "9200:9200"
    networks:
      - shared-network

  db:
    image: mysql:8.0
    container_name: tp-igl-db
    restart: always
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      timeout: 20s
      retries: 10
    networks:
      - shared-network

  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: tp-igl-backend
    command: sh -c "python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - shared-network

  grobid:
    image: grobid/grobid:0.8.0
    container_name: tp-igl-grobid
    restart: always
    networks:
      - shared-network

volumes:
  data:

networks:
  shared-network:
    driver: bridge

