version: '3.8'
services:
  elasticsearch:
    image: elasticsearch:8.12.0
    container_name: elasticsearch-container
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"
  db:
    image: mysql:8.0
    container_name: tp-igl-db
    restart: always
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]      
      timeout: 20s
      retries: 10
  grobid:
    image: lfoppiano/grobid:0.8.0-arm
    init: true
    container_name: grobid-container
    restart: always
    ports:
      - "8070:8070"

    
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: tp-igl-backend
    command: sh -c "python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - elasticsearch
volumes:
  data:
