# Generated by Django 5.0 on 2023-12-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MotCle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceBibliographique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('institutions', models.ManyToManyField(related_name='auteurs', to='moderateur.institution')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=255)),
                ('resume', models.TextField(blank=True)),
                ('texte_integrale', models.TextField(blank=True)),
                ('url_pdf', models.CharField(max_length=255)),
                ('date_publication', models.DateField()),
                ('auteurs', models.ManyToManyField(related_name='article_auteurs', to='moderateur.auteur')),
                ('mots_cles', models.ManyToManyField(related_name='article_mots_cles', to='moderateur.motcle')),
                ('references_bibliographiques', models.ManyToManyField(related_name='article_references_bibliographiques', to='moderateur.referencebibliographique')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_type', models.CharField(choices=[('admin', 'Admin'), ('regular', 'Regular'), ('moderator', 'Moderator')], max_length=10)),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('favorites', models.ManyToManyField(related_name='user_article_favorites', to='moderateur.article')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
