# Generated by Django 5.0 on 2023-12-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderateur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_valide',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='url_pdf',
            field=models.URLField(),
        ),
    ]
